### ISSUE TITLE
`render-pages` only renders index.html

### ISSUE THREAD

**Issue by craftedsystems** [loteoo/hyperapp-site-generator-starter#1]
`npm run render-pages` does render a nice _index.html_ but _about/index.html_ and _count/index.html_ end up as empty files.

**Comment by loteoo** [comment]
Thanks for the info, it "worked fine on my machine" but then I realized I get the same result as you on Netlify. I'll check out what's going on.

**Comment by loteoo** [comment]
@craftedsystems Could you bump your `hyperapp-site-generator` version to 0.0.18, and tell me if the renders work properly now? I did a async rookie mistake and only ran properly on my machine because of the slow CPU *facepalm*

I finally found the root cause of the instability now, thanks!

**Comment by craftedsystems** [comment]
fixed in new version. thx
